# Map cards to Pokedex
library(dplyr)
library(stringr)
#library(fuzzyjoin)

cards <- read.csv('data/pkmn_card_prices.csv',stringsAsFactors = F)
pokedex <- read.csv('data/pokedex_202104.csv',stringsAsFactors = F)

pokedex$name <- gsub('^Aegislash Blade Forme$','Aegislash',pokedex$name)
pokedex$name <- gsub(' Female$','',pokedex$name)
pokedex$name <- gsub(' Full Belly Mode$','',pokedex$name)
pokedex$name <- gsub(' Zen Mode$','',pokedex$name)
pokedex$name <- gsub(' Amped Form$','',pokedex$name)
pokedex$name <- gsub(' Blue-Striped Form$','',pokedex$name)
pokedex$name <- gsub(' Deoxys Attack Forme$','',pokedex$name)
pokedex$name <- gsub(' Noice Face$','',pokedex$name)
pokedex$name <- gsub(' Normal Forme$','',pokedex$name)
pokedex$name <- gsub(' Origin Forme$','',pokedex$name)
pokedex$name <- gsub(' Ordinary Forme$','',pokedex$name)
pokedex$name <- gsub(' Incarnate Forme$','',pokedex$name)
pokedex$name <- gsub(' Complete Forme$','',pokedex$name)
pokedex$name <- gsub(' Midnight Form$','',pokedex$name)
pokedex$name <- gsub(' Pirouette Forme$','',pokedex$name)
pokedex$name <- gsub(' Sensu Style$','',pokedex$name)
pokedex$name <- gsub(' Average Size$','',pokedex$name)
pokedex$name <- gsub(' Crowned (Shield|Sword)$','',pokedex$name)
pokedex$name <- gsub(' Hoopa Unbound$','',pokedex$name)
pokedex$name <- gsub(' Solo Form$','',pokedex$name)
pokedex$name <- gsub('^Wormadam Plant Cloak$','Wormadam',pokedex$name)
pokedex$name <- gsub('^Nidoranâ™‚','Nidoran m',pokedex$name)
pokedex$name <- gsub('^Nidoranâ™€','Nidoran f',pokedex$name)

cards$name_mapping <- cards$PRODUCT
cards$name_mapping <- gsub('^Rapid Strike Urshifu','Urshifu Rapid Strike Style',cards$name_mapping)
cards$name_mapping <- gsub('^Single Strike Urshifu','Urshifu Single Strike Style',cards$name_mapping)
cards$name_mapping <- gsub('^Single Strike ','',cards$name_mapping)
cards$name_mapping <- gsub('^Rapid Strike ','',cards$name_mapping)
cards$name_mapping <- gsub('Nidoran (F)','Nidoran F',cards$name_mapping)
cards$name_mapping <- gsub('^M ','',cards$name_mapping)
cards$name_mapping <- gsub('^Ancient ','',cards$name_mapping)
cards$name_mapping <- gsub('^Armor Fossil ','',cards$name_mapping)
cards$name_mapping <- gsub('^Armored ','',cards$name_mapping)
cards$name_mapping <- gsub('^Cool ','',cards$name_mapping)
cards$name_mapping <- gsub('^Detective ','',cards$name_mapping)
cards$name_mapping <- gsub("^Team Aqua's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Team Magma's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Team Rocket's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Rocket's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Dark ",'',cards$name_mapping)
cards$name_mapping <- gsub('^Shadow ','',cards$name_mapping)
cards$name_mapping <- gsub('^Surfing ','',cards$name_mapping)
cards$name_mapping <- gsub("^Light ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Shining ",'',cards$name_mapping)
cards$name_mapping <- gsub('^Flying ','',cards$name_mapping)
cards$name_mapping <- gsub('^Special Delivery ','',cards$name_mapping)
cards$name_mapping <- gsub("^______'s ",'',cards$name_mapping)
cards$name_mapping <- gsub('^Ash-','',cards$name_mapping)
cards$name_mapping <- gsub("^Ash's",'',cards$name_mapping)
cards$name_mapping <- gsub("^Blaine's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Giovanni's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Imakuni's ",'',cards$name_mapping)

cards$name_mapping <- gsub("^Koga's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Lt. Surge's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Misty's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Sabrina's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Brock's ",'',cards$name_mapping)
cards$name_mapping <- gsub("^Erika's ",'',cards$name_mapping)
cards$name_mapping <- trimws(cards$name_mapping)

cards$name_mapping <- gsub('(BW|SM|SWSH|XY)(\\d\\d+)(a)*','',cards$name_mapping)
cards$name_mapping <- gsub(' \\(.*\\)$','',cards$name_mapping)
cards$name_mapping <- gsub(' \\[.*\\]$','',cards$name_mapping)
cards$name_mapping <- gsub('\\d+(a)*','',cards$name_mapping)
cards$name_mapping <- gsub('\\d*','',cards$name_mapping)
cards$name_mapping <- gsub('\\/','',cards$name_mapping)
cards$name_mapping <- gsub('\\- ','',cards$name_mapping)
cards$name_mapping <- gsub(' -',' ',cards$name_mapping)
cards$name_mapping <- gsub('- ',' ',cards$name_mapping)
cards$name_mapping <- trimws(cards$name_mapping)

cards$name_mapping <- gsub('Lv.X$','',cards$name_mapping)
cards$name_mapping <- gsub(' Emerging Powers$','',cards$name_mapping)
cards$name_mapping <- gsub(' Guardians Rising$','',cards$name_mapping)
cards$name_mapping <- gsub(' Flashfire$','',cards$name_mapping)
cards$name_mapping <- gsub(' Staff Prerelease Promo$','',cards$name_mapping)
cards$name_mapping <- gsub(' Prerelease Promo$','',cards$name_mapping)
cards$name_mapping <- gsub(' Primal Clash$','',cards$name_mapping)
cards$name_mapping <- gsub(' Legend','',cards$name_mapping)
cards$name_mapping <- gsub(' (East|West) Sea','',cards$name_mapping)
cards$name_mapping <- gsub(' (Plant|Sandy|Trash) Cloak','',cards$name_mapping)
cards$name_mapping <- gsub(' Snow-Cloud Form',' Snowy Form',cards$name_mapping)
cards$name_mapping <- gsub('Snow-cloud Castform','Castform Snowy Form',cards$name_mapping)
cards$name_mapping <- gsub('Sunny Castform','Castform Sunny Form',cards$name_mapping)
cards$name_mapping <- gsub(' Rain Form',' Rainy Form',cards$name_mapping)
cards$name_mapping <- gsub(' Bros\\.','',cards$name_mapping)
cards$name_mapping <- gsub('Libre','',cards$name_mapping)
cards$name_mapping <- gsub('on the Ball$','',cards$name_mapping)
cards$name_mapping <- trimws(cards$name_mapping)

cards$name_mapping <- gsub('Galarian ','',cards$name_mapping)
cards$name_mapping <- gsub('Primal ','',cards$name_mapping)
cards$name_mapping <- gsub('Alolan ','',cards$name_mapping)
cards$name_mapping <- trimws(cards$name_mapping)

cards$name_mapping <- gsub(' (EX|ex)$','',cards$name_mapping)
cards$name_mapping <- gsub(' (EX|ex) ','',cards$name_mapping)
cards$name_mapping <- gsub('VMAX$','',cards$name_mapping)
cards$name_mapping <- gsub('VMAX ','',cards$name_mapping)
cards$name_mapping <- gsub('(BREAK|BREAKthrough|BREAKpoint)$','',cards$name_mapping)
cards$name_mapping <- gsub('(BREAK|BREAKthrough|BREAKpoint) ','',cards$name_mapping)
cards$name_mapping <- gsub(' Sun & Moon$','',cards$name_mapping)
cards$name_mapping <- gsub(' XY Base Set$','',cards$name_mapping)
cards$name_mapping <- gsub('(G|C|FB|E|GL|GX|BW)$','',cards$name_mapping)
cards$name_mapping <- gsub('(G|C|FB|E|GL|GX|BW) ','',cards$name_mapping)
cards$name_mapping <- gsub('Spirit Link','',cards$name_mapping)
cards$name_mapping <- gsub('Prism Star$','',cards$name_mapping)
cards$name_mapping <- gsub('Star$','',cards$name_mapping)
cards$name_mapping <- gsub('Star ','',cards$name_mapping)
cards$name_mapping <- gsub('(BW|SM|SWSH|XY)(\\d\\d+)','',cards$name_mapping)
cards$name_mapping <- gsub('(Lv\\.) \\d+','',cards$name_mapping)
cards$name_mapping <- gsub('(Lv\\.)','',cards$name_mapping)

cards$name_mapping <- trimws(cards$name_mapping)
cards$name_mapping <- gsub(' \\(.*\\)$','',cards$name_mapping)
cards$name_mapping <- gsub(' SWSH$','',cards$name_mapping)
cards$name_mapping <- gsub('V$','',cards$name_mapping)
cards$name_mapping <- gsub('(XY|SM|DP|SS|XY-P|Doll|XYa|SMa)$','',cards$name_mapping)
cards$name_mapping <- gsub(' [a-z]$','',cards$name_mapping)
cards$name_mapping <- gsub(' no\\.','',cards$name_mapping)
cards$name_mapping <- trimws(cards$name_mapping)

cards$name_mapping <- tolower(cards$name_mapping)
pokedex$name_lower <- tolower(pokedex$name)
#cards$name_mapping <- gsub("^porygonz$","porygon-z",cards$name_mapping)
cards$name_mapping <- gsub(' ex$','',cards$name_mapping)
#cards$name_mapping <- gsub("^hooh$","ho-oh",cards$name_mapping)

cards$name_mapping <- ifelse(is.na(str_locate(pattern =' &| and|, ',cards$name_mapping)[,1])
                             ,cards$name_mapping
                             ,substr(cards$name_mapping,0,str_locate(pattern =' &| and|, ',cards$name_mapping)[,1]))
cards$name_mapping <- gsub('\\,$','',cards$name_mapping)
cards$name_mapping <- trimws(cards$name_mapping)


pokedex <- pokedex[,c("name_lower","name","pokedex_number","generation")]
output <- left_join(cards, pokedex, by = c("name_mapping" = "name_lower"))

name_check <- output[c("PRODUCT","name_mapping","name")]

non_matches <- filter(name_check,is.na(name))
match_rate <- 1 - nrow(non_matches)/nrow(cards)

write.csv(name_check,"name_check.csv",row.names = F)
write.csv(output,"data/pkmn_card_prices_and_pokedex.csv",row.names = F)